apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-allowed
  labels:
    app.kubernetes.io/name: curl-allowed
spec:
  containers:
    - name: curl-container
      image: curlimages/curl
      tty: true
      stdin: true
      stdinOnce: true
      args:
      - sh
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-forbidden
  labels:
    app.kubernetes.io/name: curl-forbidden
spec:
  containers:
    - name: curl-container
      image: curlimages/curl
      tty: true
      stdin: true
      stdinOnce: true
      args:
      - sh