# Pull in the layer of the base image: golang:1.23.3-alpine


# Set author label: LABEL author=[YOUR-EMAIL]


# Set working directory: `/opt`


# Copy local files `go.mod` and `main.go` to the working directory


# List items in the working directory (ls -lsa) and show content of the `main.go`file (cat)


# Build the app (CGO_ENABLED=0 go build -o /usr/myapp) and show the /usr directory  (ls -lsa)


# Expose the port 8888


# Set the entrypoint to run the app
